// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCdxfEY8zS6m8pZd-_R9zYVvNGwqzZHz8o',
    appId: '1:927078353990:web:20dd81bb513d0feb8d4e47',
    messagingSenderId: '927078353990',
    projectId: 'firebase-auth-new',
    authDomain: 'fir-auth-new-11fc5.firebaseapp.com',
    storageBucket: 'firebase-auth-new.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyClSdhWyD3Ddm8eiQECCsZuRYZpWvu5pio',
    appId: '1:927078353990:android:617c2e43a7367bef8d4e47',
    messagingSenderId: '927078353990',
    projectId: 'firebase-auth-new',
    storageBucket: 'firebase-auth-new.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD98dpY-KItc5twqk9uB-TByBFRO6EOIKs',
    appId: '1:927078353990:ios:18a771ce6e5c801f8d4e47',
    messagingSenderId: '927078353990',
    projectId: 'firebase-auth-new',
    storageBucket: 'firebase-auth-new.appspot.com',
    iosClientId: '927078353990-o3hqjc4h1tkb9a148856tfcms9letteb.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaseAuthNew',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD98dpY-KItc5twqk9uB-TByBFRO6EOIKs',
    appId: '1:927078353990:ios:18a771ce6e5c801f8d4e47',
    messagingSenderId: '927078353990',
    projectId: 'firebase-auth-new',
    storageBucket: 'firebase-auth-new.appspot.com',
    iosClientId: '927078353990-o3hqjc4h1tkb9a148856tfcms9letteb.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaseAuthNew',
  );
}
